appsetup/urls.py
"""
Definition of urls for setup.
This mostly ties urls to methods in views.py
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views


# variables inherited from django, replaced string value
# handler404 = 'app.views.error_handler_404'
# handler500 = 'app.views.error_handler_500'

# set the urls to views & gives them a name
# example : path('about/', views.about, name='about')
#  1st part (ex: "about/") is url part
#  2nd part (ex: views.about) is method that controls how page looks like the page looks
#  name part allows references to it (ex: name="about" allows href="{% url 'about' %}")
urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('admin_settings/', views.admin_settings, name="admin_settings"),
    path('history/', views.history, name="history"),
    path('people/', views.people, name="people"),
    path('login/',
         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Log in',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
    path('accounts/register/', views.register_view, name="signup"),

    path('user/password/', views.change_password, name='change_password'),
    path('user/profile/', views.profile, name ="profile"),
    path('user/settings/', views.user_settings, name="user_settings"),


    path('inventory/', views.InventoryIndex.as_view(), name='inventory_index'),
    path('inventory/<slug:search>', views.InventoryIndex.as_view(), name='inventory_index_searched'),
    path('inventory/items/<int:page>', views.items, name='items'),
    path('inventory/items/<int:page>/<slug:searchby>/<slug:searched>', views.items, name='items_searched'),
    path('inventory/create_item/', views.ItemCreateView.as_view(), name='create_item'),
    path('inventory/update_item/<int:pk>', views.ItemUpdateView.as_view(), name='update_item'),
    path('inventory/read_item/<int:pk>', views.ItemReadView.as_view(), name='read_item'),
    path('inventory/delete_item/<int:pk>', views.ItemDeleteView.as_view(), name='delete_item'),
    path('inventory/read_vendor/<int:pk>/', views.ReadVendor.as_view(), name='ReadVendor'),

    path('vendors/<int:item>/', views.VendorIndex.as_view(), name='VendorList'),
    path('vendors/<int:item>/delete_item/<int:pk>/', views.VendorDeleteView.as_view(), name='delete_vendor'),
    path('vendors/<int:item>/create_item/', views.VendorCreateView.as_view(), name='create_vendor'),
    path('vendors/<int:item>/update_item/<int:pk>/', views.VendorUpdateView.as_view(), name='update_vendor'),
    path('vendors/<int:itemfk>', views.vendors, name='vendorslist'),

    path('users/', views.PeopleIndex.as_view(), name="people_index"),
    path('users/<slug:search>', views.PeopleIndex.as_view(), name='people_index_searched'),
    path('users/update_user/<int:pk>', views.UserUpdateView.as_view(), name='update_user'),
    path('users/delete_user/<int:pk>', views.UserDeleteView.as_view(), name='delete_user'),
    path('users/people/', views.users_list, name="user_list"),

]

app/models.py
"""
Definition of models.
"""

# from xmlrpc.client import DateTime
# from django import db
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser # , User
# from django_boost.models.fields import AutoOneToOneField
from django.utils.timezone import now
from annoying.fields import AutoOneToOneField
from django.contrib.auth.models import Group

# Create your models here.
# created a table for admin settings
# print(now())

RANK_CHOICES = (
    ('Admin', 'Admin'),
    ('Manager', 'Manager'),
    ('Viewer', 'Viewer'),
)
RANK_GROUPS = ["Admin", "Manager", "Viewer"]
class CustomUser(AbstractUser):
    rank = models.CharField(max_length=10,choices=RANK_CHOICES,default="Viewer")

    def save(self, *args, **kwargs):
        # remove user from rank groups
        query_set = Group.objects.filter(user = self.pk)
        for g in query_set:
            if g.name in RANK_GROUPS:
                g.user_set.remove(self)
                # self.user.groups.remove(group)

        # assign user to new rank group
        if self.rank == "Admin":
            group, created = Group.objects.get_or_create(name='Admin')
        elif self.rank == "Manager":
            group, created = Group.objects.get_or_create(name='Manager')
        elif self.rank == "Viewer":
            group, created = Group.objects.get_or_create(name='Viewer')
        group.user_set.add(self.pk)
        super(CustomUser, self).save(*args, **kwargs)



User = get_user_model()

class recent_alerts(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=45)
    
    class Meta:

        db_table="recent_alerts"

#new history page
class recent_new_user(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    descrption = models.CharField(max_length=250)
    created_date = models.DateTimeField(default=now, editable=False)

    class Meta:
        
        db_table="recent_new_user"

class recent_new_item(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE)
    description = models.CharField(max_length=45)
    newItem = models.CharField(max_length=45)

    class Meta:

        db_table = "recent_new_item"

# Mockup purchase history db. Inactive, need to create db in Heroku. -Thomas
class purchase_history(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    descrption = models.CharField(max_length=45)
    # add time attribute to this and other audit logs?

    class Meta:

        db_table="purchase_history"

# Mockup inventory changes db. Inactive, need to create db in Heroku. -Thomas
class inventory_changes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    descrption = models.CharField(max_length=45)
    # add time attribute to this and other audit logs?

    class Meta:

        db_table="inventory_changes"

class history(models.Model):
    id = models.IntegerField(primary_key= True)
    description = models.CharField(max_length=100)
    time = models.DateField()

    class Meta:
        db_table = "history"
       

# for settings, left is value right is appearance
FONT_CHOICES = (
    ('Arial', 'Arial'),
    ('Courier New', 'Courier'),
    ('Times New Roman', 'Times New Roman'),
    ('Verdana', 'Verdana'),
)
PAGINATE_BY_CHOICES = (
    (5, '5'),
    (10, '10'),
    (15, '15'),
    (25, '25'),
    (50, '50'),
    (100, '100'),
    (0, 'All')
)
class personal_user_settings(models.Model):
    user = AutoOneToOneField(to=User, on_delete=models.CASCADE, primary_key=True, related_name="user_profile")
    font_type = models.CharField(max_length=20, choices=FONT_CHOICES, default='Arial')
    paging_by = models.PositiveSmallIntegerField(choices=PAGINATE_BY_CHOICES, default=10)

    class Meta:
        db_table = "personal_user_settings"

class global_settings(models.Model):

    allow_inventory_changes = models.BooleanField(default=False)
    allow_adding_new_users = models.BooleanField(default=False)
    allow_inventory_purchases = models.BooleanField(default=False)
    allow_paring_data = models.BooleanField(default=False)

    class Meta:
        db_table = "global_settings"

class Item(models.Model):

    title = models.CharField(max_length=50)
    alert = models.BooleanField(default = True)
    image_path = models.CharField(max_length = 500, blank=True)
    stock = models.PositiveIntegerField(default=0)
    threshold = models.PositiveIntegerField(default=1)
    part_number = models.CharField(max_length = 15, blank=True)

    def save(self, *args, **kwargs):
        if self.stock > self.threshold:
            self.alert = False
        else:
            self.alert = True
        super(Item, self).save(*args, **kwargs)


class Vendor(models.Model):
    path = models.URLField(max_length=500)   
    name = models.CharField(max_length=100)
    itemfk = models.ForeignKey(Item, unique=False, on_delete=models.CASCADE)
    
# Temporary, deprecates when File Upload is ready.
class mock_inventory(models.Model):
    item = models.IntegerField(primary_key = True)
    alert = models.BooleanField(default = True)
    name = models.CharField(max_length = 100)
    image = models.CharField(max_length = 500)
    amount = models.IntegerField()
    description = models.CharField(max_length = 500)

    class Meta:
        db_table = "mock_inventory"

app/templates/app/_footer.html
<footer>
    <p>&copy; {{ year }} - My Django Application</p>
</footer>

app/templates/app/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog mt-5">
      <div class="modal-content">
      </div>
    </div>
  </div>
  
  <div class="modal fade" tabindex="-1" role="dialog" id="modal">
    <div class="modal-dialog mt-5" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
  

app/templates/app/_nav.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="/">ACR</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">

        
        <li class="nav-item {% if 'about' in request.path %} active {% endif %}">
          <a class="nav-link " href="{% url 'about' %}">About</a>
        </li>
        {% if user.is_authenticated  %}

          {% if perms.app.view_customuser %}
            <li class="nav-item {% if 'admin_settings' in request.path %} active {% endif %}">
              <a class="nav-link " href="{% url 'admin_settings' %}">Admin Settings</a>
            </li>
          {% endif %}
          
          {% if perms.app.change_global_settings %}
            <li class="nav-item {% if 'people' in request.path %} active {% endif %}">
              <a class="nav-link " href="{% url 'people_index' %}">Users</a>
            </li>
          {% endif %}

          {% if perms.app.view_history %}
            <li class="nav-item {% if 'history' in request.path %} active {% endif %}">
              <a class="nav-link " href="{% url 'history' %}">History</a>
            </li>
          {% endif %}

          {% if perms.app.view_item %}
            <li class="nav-item {% if 'inventory' in request.path %} active {% endif %}">
              <a class="nav-link " href="{% url 'inventory_index' %}">Inventory</a>
            </li>
          {% endif %}

        {% endif %}
      </ul>

        {% include 'app/loginpartial.html' %}
     </div>
  </nav>

app/templates/app/_paging.html
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            <!-- If outside of 'x' range (look at middle) then -->
            {% if page_obj.has_previous and page_obj.number|add:'-3' > 1 %}
                <!-- The move to first page -->
                <li class="page-item">
                    <a class="page-link" href="?page=1{{extra}}" aria-label="Previous">
                        1                        
                    </a>
                </li>
                {% if page_obj.number|add:'-4' != 1 %}
                <li class="page-item">
                    <!-- The fill in page to go to -->
                    <a class="go-to-dot page-link" data-toggle="modal" data-target="#exampleModal" id="go_to_page_1">
                        <span class="fa-solid fa-ellipsis" style="color: blue;"></span>
                    </a>
                </li>
                {% endif %}
            {% endif %}
            
            {% for n in page_obj.paginator.page_range %}
            {% if page_obj.number == n %}
            <!-- current page -->
                <li class="page-item active">
                <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
                </li>
            {% elif n > page_obj.number|add:'-4' and n < page_obj.number|add:'4' %}
                <!-- display 'x'-1 pages to left and right of middle/current page -->
                <li class="page-item"><a class="page-link" href="?page={{ n }}{{extra}}">{{ n }}</a></li>
            {% endif %}
            {% endfor %}
            </li>
            <!-- If outside of 'x' range (look at middle) then -->
            {% if page_obj.has_next and page_obj.number|add:'3' <  page_obj.paginator.num_pages %}
              {% if page_obj.number|add:'4' != page_obj.paginator.num_pages %}
                <li class="page-item">
                  <!-- The fill in page to go to -->
                  <!-- <input class="page-link" style="width:40px" type="text" id="last_go_to" name="last_go_to" placeholder="..."><br> -->
                  <a class="go-to-dot page-link" data-toggle="modal" data-target="#exampleModal" id="go_to_page_2">
                      <span class="fa-solid fa-ellipsis" style="color: blue;"></span>
                  </a>
                </li>
              {% endif %}
              <li class="page-item">
                <!-- The move to last page -->
                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{{extra}}" aria-label="Next">
                  {{ page_obj.paginator.num_pages }}
                </a>
              </li>

            {% endif %}   
        </ul>
    </nav>

    <div class="modal" tabindex="-1" role="dialog" id="exampleModal">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title"></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <p>Go to page (1 to {{ page_obj.paginator.num_pages }}):</p>
              <input class="form-control" id="go_to_page" oninput="this.value = this.value.replace(/[^0-9]/g, '').replace(/(\..*?)\..*/g, '$1');">
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary" id="go_to_page_btn">Go</button>
            </div>
          </div>
        </div>
      </div>

<script type="text/javascript">
    var go_to_page = document.getElementById("go_to_page");
    var go_to_page_btn = document.getElementById("go_to_page_btn");

    go_to_page_btn.addEventListener("click", function(event) {
        var num_pages = "{{ page_obj.paginator.num_pages}}";
        var extra = "{{extra}}".replaceAll("amp;","");
        var page = go_to_page.value;
        if (parseInt(page) < 0 || parseInt(page) == 0) { page = "1";}
        if (parseInt(page) > parseInt(num_pages) ) {page = num_pages; }
        var loc = window.location.href;
        loc = loc.substr(0, loc.lastIndexOf("/"));
        location.replace(`${loc}/?page=${page}${extra}`);
    });
    document.addEventListener('keypress', function (e) {
          if (e.key === 'Enter') {
              if ($("#exampleModal").is(':visible')) {
                var num_pages = "{{ page_obj.paginator.num_pages}}";
                var extra = "{{extra}}".replaceAll("amp;","");
                var page = go_to_page.value;
                if (parseInt(page) < 0 || parseInt(page) == 0) { page = "1";}
                if (parseInt(page) > parseInt(num_pages) ) {page = num_pages; }
                var loc = window.location.href;
                loc = loc.substr(0, loc.lastIndexOf("/"));
                location.replace(`${loc}/?page=${page}${extra}`);
              }
          }
        });
</script>

app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}
    <br><br>
    <div class="container mt-5 mb-5">
        <h1 class="modal-title text-center">{{ title }}</h1>
    </div>

    <div class="container mt-3">
        <div class="row">
          <div class="col">
            <div class="row">
              <div class="col ">
                <h3>{{ message }}</h3>
                <p>This is currently in development.<br>
                    Expected to finish in upcoming 2022.</p>
                    <!-- <hr> -->
              </div>
            </div>
          </div>
        </div>
    </div>

{% endblock %}

app/templates/app/admin_settings.html
{% extends "app/layout.html" %}

{% block content %}
<br><br>
<h2>{{ title }}</h2>
<head>
	<title>{{ title }}</title>
<!--	<link rel="stylesheet" type="text/css" href="../../static/app/content/settings_page.css">-->
<!--	<link rel="stylesheet" type="text/css" href="../../static/app/content/style3.css">-->
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'app/content/style3.css' %}" />
	<style>
		h2{
   			 text-align: center;
   			 color: #000000;
  			  padding: 20px;
   			 text-decoration: overline underline;
		}
	</style>
	
</head>

<body>
	<hr>
	<form method="POST">
		{% csrf_token %}
		<h3>Global Settings</h3> <br>
		{{global_form.as_p|linebreaks}} <br>
		<hr>

		<button type="button" class="cancelbtn" onclick="window.location='';"> Cancel</button>
		<button type="submit" class="savebtn">Save</button>
	</form>
	
	
</body>


{% endblock %}

app/templates/app/adminhomepage.html
{% extends 'app/layout.html' %}

{% block content %}
<head>    
  <title>Admin Homepage</title>
<!--    <link rel="stylesheet" type="text/css" href="css/style2.css">-->
  {% load static %}
  <!-- <link rel="stylesheet" type="text/css" href="{% static 'app/content/style.css' %}" /> -->
  <style>
		h2{
   			 text-align: center;
   			 color: #000000;
  			  padding: 20px;
   			 text-decoration: overline underline;
		}

		h3{
            text-align: center;
            text-decoration: underline;
        }

    .nostretch{
        width: 100px !important; 
      }
        
	</style>
</head>   


  <br><br>
  <div class="container mt-5 mb-5"></div>
    <h1 class="modal-title text-center">Admin Homepage</h1>
  </div>
  {% include "app/_modal.html" %}
  <div class="container mt-3">
    
    <div class="row">
      <div class="col">
        <div class="row">
          <div class="col-12 mb-4">  
              <!-- Upload File Button WIP -->
              <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="myfile">
                <button class = "ml-auto btn btn-primary" type="submit">Upload</button>
              </form>
            </div>
          </div>

          <div class="table" style="height:700px;overflow:auto;">
          
          <table id="admin-table" class="table">

          <thead>
            <tr>
              <th class="text-center" scope="col">Event</th>
              <th class="text-center" scope="col">UID</th>
              <th class="text-center" scope="col">Time</th>
            </tr>
            </thead>
            <tbody>
              {% for i in history %}
              <tr>
                <td class="text-center">{{i.descrption}}</td>
                <td class="text-center">{{i.user_id}}</td>
                <td class="text-center">{{i.created_date}}</td>
              </tr>
            {% endfor %}
          
            </tbody>
          </table>
          {% include "app/_paging.html" %}

          </div>
        </div>
      </div>
    </div>
  </div>
</body>

{% endblock content %}

app/templates/app/form_page.html
{% extends "app/layout.html" %}
{% load widget_tweaks %}



{% block content %}
<br><br>
<head>
	
	<style>
		.switchLabel{
			position: relative;
			display: block;
			width: 40px;
			height: 20px;
			margin-bottom: 10px;
		}
		.switchLabel input{
			display: none;
		}

		.slidinggrove{
			position: absolute;
			top: 0;
			right: 0;
			left: 0;
			bottom: 0;
			background: #ABABAB;
			border-radius: 10px;
			transition: all 0.3s ease;
		}
		.slidinggrove:after{
			position: absolute;
			content: "";
			width: 18px;
			height: 18px;
			border-radius: 50%;
			background: #FFF;
			top: 1px;
			left: 1px;
			transition: all 0.3s ease;
		}

		input:checked + .slidinggrove {
			background: #03A9F4;
		}
		input:checked + .slidinggrove:after {
			transform: translateX(20px);
		}

		.labelterm{
			position: relative;
			top: 5px;
			margin-left: 65px;
		}
			  
	</style>
	
</head>


	<form method="POST">
		{% csrf_token %}
		<div class="container mt-3 ml-5 mr-5">
			<div class="row">
			  	<div class="col">
					<div class="row">
				  		<div class="col-10 mb-2">
							<h2 class="mt-5 mb-0 text-center" >{{ title }}</h2>
							<div class="modal-header"></div>

							<div class="modal-body">

								<div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
								{% for error in form.non_field_errors %}
									{{ error }}
								{% endfor %}
								</div>
							
								{% for field in form %}
								<div class="form-group">
									{% if field.field.widget.input_type == "checkbox"%}
										{% comment %} implemnt custom "checkbox" which is toggle slider {% endcomment %}
										<div class="d-flex justify-content-between">
											<div><label for="{{ field.id_for_label }}">{{ field.label }} </label></div>
											<div class="switchLabel text-end">
												{{ field }}
												
												<div class="slidinggrove"> </div>
												<label class="switchLabel" for="{{ field.id_for_label }}" ></label>
											</div>
										</div>
									{% elif field.field.widget.input_type == "select" %}
										<div class="d-flex justify-content-between">
											<div>
												<label for="{{ field.id_for_label }}">{{ field.label }}</label>
											</div>
											<div class="ml-auto">
												{% render_field field class="form-select" style="text-align:center;"  placeholder=field.label %} 
											</div>
										</div>
									
									{% else %} 
										<div class="d-flex justify-content-between">
											<div>
												<label for="{{ field.id_for_label }}">{{ field.label }}</label>
											</div>
											<div class="ml-auto">
												{% render_field field class="form-control" style="text-align:center;"  placeholder=field.label %} 
											</div>
										</div>
									{% endif %}

									<div class="{% if field.errors %} invalid{% endif %}">
										{% for error in field.errors %}
											<p class="help-block">{{ error }}</p>
										{% endfor %}
									</div>
								</div>
								{% endfor %}
							</div>
							
							<div class="modal-footer">
								<button type="button" class="btn btn-danger" onclick="window.location='';"> Cancel</button>
								<button type="submit" class="btn btn-primary">Update</button>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</form>
	
	
{% endblock %}

app/templates/app/history.html
<!--<!DOCTYPE html>-->
{% extends "app/layout.html" %}

{% block content %}
<head>
	<title>History</title>
<!--	<link rel="stylesheet" type="text/css" href="css/style2.css">-->
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'app/content/style2.css' %}" />

	<style>
		table {
		  border-collapse: collapse;
		  width: 100%;
		}
		
		th, td {
		  padding: 8px;
		  text-align: left;
		  border-bottom: 1px solid #ddd;
		}
		
		tr:hover {background-color: coral;}

		h2{
   			 text-align: center;
   			 color: #000000;
  			  padding: 20px;
   			 text-decoration: overline underline;
		}

		h3{
            text-align: center;
            text-decoration: underline;
        }
	
	</style>

</head>
<body>
	<br><br>
	<h2>History</h2><br>

	<!-- <hr> NON-FUNCTIONAL. Commented out for now.

	<div class="topnav">
		<div class="search-container">
			<form action="/action_page.php">
				<input type="text" placeholder="Search.." name="search">
				<button type="submit"><i class="fa fa-search"> Go
				</i></button>
			</form>
		</div>
	</div>
	<hr>

			TODO: Figure out why css file changes not applying. Sort alerts by time. Implement different buttons
			for different types of sorting? Only displays and hides one item in each db.
	<h3>Audit Log</h3>	-->

	<div class="table" style="height:600px;overflow:auto;">
		<table>
			<!-- Table Headers -->
			<tr id>
				<th>Event</th>
				<th>UID</th>
				<th>Time</th> 
			</tr>
			{% for i in history %}
				{% if "acess" in i.descrption %}
					<tr class ="accesses" style.display = 'none'>
						<td>{{i.descrption}}</td>
                		<td>{{i.user_id}}</td>
                		<td>{{i.created_date}}</td>
					</tr>
				{% elif "change" in i.descrption %}
					<tr class ="changes" style.display = 'none'>
						<td>{{i.descrption}}</td>
                		<td>{{i.user_id}}</td>
                		<td>{{i.created_date}}</td>
					</tr>
				{% elif "Log" in i.descrption %}
					<tr class ="logins" style.display = 'none'>
						<td>{{i.descrption}}</td>
                		<td>{{i.user_id}}</td>
                		<td>{{i.created_date}}</td>
					</tr>
				{% endif %}
			{% endfor %}
		</table>
	</div>	
	<hr>

	<div class="containerSettings">
		
		<label class="containerSettings">Hide Access History
			<input type="checkbox" id="accesses_check" checked onclick="view_accesses()">
			<span class="checkmark"></span>
		</label>

		<label class="containerSettings">Hide Change History
			<input type="checkbox" id="changes_check" checked onclick="view_changes()">
			<span class="checkmark"></span>
		</label>
		
	</div>
</body>

<script>
	function view_accesses() {
	  	var checkBox = document.getElementById("accesses_check");
		var accesses = document.getElementsByClassName('accesses');
		if (checkBox.checked == false) {
			for (var row of accesses) {
				row.style.display = 'table-row';
			}
		} else {
			for (var row of accesses) {
				row.style.display = 'none';
			}
		}
	}

	function view_changes() {
		var checkBox = document.getElementById("changes_check");
		var changes = document.getElementsByClassName('changes');
		if (checkBox.checked == false) {
			for (var row of changes) {
				row.style.display = 'table-row';
			}
		} else {
			for (var row of changes) {
				row.style.display = 'none';
			}
		}
	}
	
	function view_login() {
		var checkBox = document.getElementById("login_check");
		var logins = document.getElementsByClassName('logins');
		if (checkBox.checked == false) {
			for (var row of logins) {
				row.style.display = 'table-row';
			}
		} else {
			for (var row of logins) {
				row.style.display = 'none';
			}
		}
	}
</script>

{% endblock %}

app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}
<div class="jumbotron">
    <h1>Django</h1>
    <p class="lead">Django is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://www.djangoproject.com/" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<!--<div class="row">-->
<!--    <div class="col-md-4">-->
<!--        <h2>Getting started</h2>-->
<!--        <p>-->
<!--            Django gives you a powerful, patterns-based way to build dynamic websites that-->
<!--            enables a clean separation of concerns and gives you full control over markup-->
<!--            for enjoyable, agile development.-->
<!--        </p>-->
<!--        <p><a class="btn btn-default" href="https://djangobook.com/django-tutorials/">Learn more &raquo;</a></p>-->
<!--    </div>-->
<!--    <div class="col-md-4">-->
<!--        <h2>Get more libraries</h2>-->
<!--        <p>The Python Package Index is a repository of software for the Python programming language.</p>-->
<!--        <p><a class="btn btn-default" href="https://pypi.org/">Learn more &raquo;</a></p>-->
<!--    </div>-->
<!--    <div class="col-md-4">-->
<!--        <h2>Microsoft Azure</h2>-->
<!--        <p>You can easily publish to Microsoft Azure using Visual Studio. Find out how you can host your application using a free trial today.</p>-->
<!--        <p><a class="btn btn-default" href="http://azure.microsoft.com">Learn more &raquo;</a></p>-->
<!--    </div>-->
<!--</div>-->

{% endblock %}

app/templates/app/login old came with django.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load static %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}